### ISSUE TITLE
rc1 thoughts

### ISSUE THREAD

**Issue by rofl0r** [libtom/libtomcrypt#244]
just a few thoughts that came to mind when playing with the rc1 tarball.

- tarball is named cryptxxxx.tar.xz but unpacks to libtomcryptxxxx. that's a bit unexpected and not really following best practices. either the tarball should be named libtomcryptxxx.tar.xz (imo better), or the contained directory cryptxxx.
- cding into the directory and running `make` yields:
```
/tmp/libtomcrypt-1.18.0-rc1 $ make
   * gcc src/ciphers/aes/aes.o
/tmp/libtomcrypt-1.18.0-rc1 $
```
it builds a single .o file and returns. weird.
- useless files: there are several files like check_source.sh, coverage.sh, .travis.yml, helper.pl, hooks in the TLD. i doubt they are useful for a release tarball, even less so in the TLD where one goes looking for build instructions
- info in README.md seems to be useless for a release tarball. the information one looks for (how to build) is not contained.

due to lack of building instructions, i didn't yet suceed making the build.

**Comment by rofl0r** [comment]
```
$ du -h doc/
1.2M    doc/
```
doc directory is very big and contains documentation that's not possible to look at in the terminal (where one typically tries to get it to compile, and read the documentation in order to find out how). i would suggest that instead of shipping .tex, .pdf, and .doxyfile, a generated text-only documentation is more suitable. the pdf could be distributed separately (a link next to the release tarball link), in order to make the source tarball smaller.

**Comment by rofl0r** [comment]
```
3.7M    ./notes
```
i dont know what notes is, but it's big and it doesn't look like it need to be distributed in the release tarball, too.

**Comment by rofl0r** [comment]
what i do in my projects is having a script that generates the release tarball from a local git checkout, after removing all unnecessary stuff.
https://github.com/sabotage-linux/gettext-tiny/blob/master/create-dist.sh#L19

**Comment by rofl0r** [comment]
i just looked at the news entry on the libtom homepage, and it mentions that one needs to get a recent libtommath separately. however, i can't find a libttommath download on the website. i guess it would be helpful to also provide info on which libttommath version is compatible, and where to get it.

**Comment by sjaeckel** [comment]
thanks a lot for the feedback

> cding into the directory and running make ... builds a single .o file and returns. weird.

bug fixed 3806629e9e28abae3c2eff0c7513a24e20f8ba09

The following 4 points are due to the historical way how libtomcrypt was always distributed, which probably doesn't make 100% sense today (in the times of git), but I think we should keep it like that for now. This release was meant as a drop-in replacement of people using 1.17 so we tried to break not that much things...

> tarball is named cryptxxxx.tar.xz but unpacks to libtomcryptxxxx. that's a bit unexpected and not really following best practices. either the tarball should be named libtomcryptxxx.tar.xz (imo better), or the contained directory cryptxx

The naming was always like that and to keep changes in the packagers' code small (for now) we just kept this naming as it was.

> useless files: there are several files like check_source.sh, coverage.sh, .travis.yml, helper.pl, hooks in the TLD. i doubt they are useful for a release tarball, even less so in the TLD where one goes looking for build instructions

I always liked the fact that the tarball contains "everything"<sup>TM</sup>

It's true that there a no build instructions anywhere, besides some of these scripts where you can see how the software is built and run... I'll add a section with build instructions to the readme.

> doc directory is very big and contains documentation that's not possible to look at in the terminal (where one typically tries to get it to compile, and read the documentation in order to find out how). i would suggest that instead of shipping .tex, .pdf, and .doxyfile, a generated text-only documentation is more suitable. the pdf could be distributed separately (a link next to the release tarball link), in order to make the source tarball smaller.

yeah, the PDF is pretty big, but falls in the category "distribute everything"/"was always like that"

regarding the doc@terminal: e767451557c9e728101626edfe8e6f9ef6ec0a99 fine?

> i dont know what notes is, but it's big and it doesn't look like it need to be distributed in the release tarball, too.

c.f. "distribute everything" + it contains a lot of test-related things that are required if you want to run the complete testsuite

> i just looked at the news entry on the libtom homepage, and it mentions that one needs to get a recent libtommath separately. however, i can't find a libttommath download on the website. i guess it would be helpful to also provide info on which libttommath version is compatible, and where to get it.

uhm, the main page www.libtom.net contains a table with all the latest versions?! Also I thought "up-to-date" is clear enough to mean "at least the latest version at the point of this news posting" :-) but I'll update the news entry with a bit more detailed information around that.

> what i do in my projects is having a script that generates the release tarball from a local git checkout, after removing all unnecessary stuff.

we also already had discussions about cleaning up, moving things around, not distributing everything, etc. and we'll have a look into that after the release.

**Comment by karel-m** [comment]
> there a no build instructions anywhere

There is a chapter in doc called "Configuring and Building the Library" (which probably needs an update). However, having a basic build related info in README would be fine.

> what i do in my projects is having a script that generates the release tarball from a local git checkout

The approach we have chosen utilises `git archive` see `zipup` target in `makefile_include.mk`

**Comment by buggywhip** [comment]
Here are my first round comments.  

Using "make -f makefile.shared" on OSX, it only compiled aes.  Fixed?

The second try was with "make -f makefile.shared all" and it went very smoothly.  However...

Unlike most packages (and older LTC versions IIRC), v1.18rc1 buries [virtually] all build products in the hidden dir .libs instead of leaving them on the TLD.  Only libtomcrypt.la remains at the top level and .libs contains:
	libtomcrypt.0.dylib
	libtomcrypt.a
	libtomcrypt.dylib -> libtomcrypt.0.dylib
	libtomcrypt.la -> ../libtomcrypt.la
	libtomcrypt.lai

I'd like to see all in the TLD because, 1) consistency with most other packages, 2) it provides quick verification that indeed the products were generated as promised, and 3) there are times you don't want to do the classic install, but depending on your project, use a product or two somewhere else.  Both are hard to satisfy when you need to dig around in a dir not otherwise visible.

And yes, build instructions would be nice/necessary.

This went much cleaner than earlier versions of LTC.  ...MUCH cleaner.  Tx.

More later...

**Comment by buggywhip** [comment]
Here are my first round comments.  

Using "make -f makefile.shared" on OSX, it only compiled aes.  Fixed?

The second try was with "make -f makefile.shared all" and it went very smoothly.  However...

Unlike most packages (and older LTC versions IIRC), v1.18rc1 buries [virtually] all build products in the hidden dir .libs instead of leaving them on the TLD.  Only libtomcrypt.la remains at the top level and .libs contains:
	libtomcrypt.0.dylib
	libtomcrypt.a
	libtomcrypt.dylib -> libtomcrypt.0.dylib
	libtomcrypt.la -> ../libtomcrypt.la
	libtomcrypt.lai

I'd like to see all in the TLD because, 1) consistency with most other packages, 2) it provides quick verification that indeed the products were generated as promised, and 3) there are times you don't want to do the classic install, but depending on your project, use a product or two somewhere else.  Both are hard to satisfy when you need to dig around in a dir not otherwise visible.

And 4) products in the TLD serves as an immediate reminder a "make clean" may be in order.

And yes, build instructions would be nice/necessary.

This went much cleaner than earlier versions of LTC.  ...MUCH cleaner.  Tx.

More later...

**Comment by sjaeckel** [comment]
> Using "make -f makefile.shared" on OSX, it only compiled aes.  Fixed?

Yep, same issue as reported by @rofl0r and fixed by the same commit as mentioned above.

> Unlike most packages (and older LTC versions IIRC), v1.18rc1 buries [virtually] all build products in the hidden dir .libs instead of leaving them on the TLD.  Only libtomcrypt.la remains at the top level and .libs contains: ...

IIUC that's not our decision where the build products reside, but `(g)libtool`'s (also I just tried and built 1.17 which has the same behavior).

> 3) there are times you don't want to do the classic install, but depending on your project, use a product or two somewhere else

I see what you're meaning to do, probably something like this is suitable as well... `make -j9 install -f makefile.shared  PREFIX=/folder/you/choose` which then installs the headers to `/folder/you/choose/include` and the library to `/folder/you/choose/lib`!?

**Comment by buggywhip** [comment]
> On 9Jul, 2017, at 10:58 PM, Steffen Jaeckel <notifications@github.com> wrote:
> Unlike most packages (and older LTC versions IIRC), v1.18rc1 buries [virtually] all build products in the hidden dir .libs instead of leaving them on the TLD. Only libtomcrypt.la remains at the top level and .libs contains: ...
> 
> IIUC that's not our decision where the build products reside, but (g)libtool's (also I just tried and built 1.17 which has the same behavior).
> 
I understand and accept.

...but I reserve the right to not like it. ;-)

Off topic: LTM goes too far the other way.  Because sources are top level, so are the .o and .lo files.  No need for any extra reminder to run "make clean".

> there are times you don't want to do the classic install, but depending on your project, use a product or two somewhere else
> I see what you're meaning to do, probably something like this is suitable as well... make -j9 install -f makefile.shared PREFIX=/folder/you/choose which then installs the headers to /folder/you/choose/include and the library to /folder/you/choose/lib!?
> 
Still more than what I need for my use case.  A simple symlink to .libs followed by a double click will allow easy access to the libs.  I will add the symlink to my crib notes.  ...perhaps a hint in the build instructions?

-----

And then this happened while compiling ltm_desc.c  (LTC_MILLER_RABIN_REPS undefined)

glibtool: compile:  gcc -DUSE_LTM -DLTM_DESC -I/usr/local/include -I./src/headers/ -Wall -Wsign-compare -Wshadow -DLTC_SOURCE -Wextra -Wsystem-headers -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wno-type-limits -O3 -funroll-loops -fomit-frame-pointer -Wno-nullability-completeness -DGIT_VERSION=\"1.18.0-rc1\" -c src/math/ltm_desc.c  -fno-common -DPIC -o src/math/.libs/ltm_desc.o
src/math/ltm_desc.c:407:12: error: use of undeclared identifier 'LTC_MILLER_RABIN_REPS'
       b = LTC_MILLER_RABIN_REPS;
           ^
src/math/ltm_desc.c:432:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long)' with an expression of type 'int (*)(void *, ltc_mp_digit)' (aka 'int (*)(void *, unsigned long long)') [-Wincompatible-function-pointer-types]
   &set_int,
   ^~~~~~~~
src/math/ltm_desc.c:437:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long)' with an expression of type 'int (*)(void *, ltc_mp_digit)' (aka 'int (*)(void *, unsigned long long)') [-Wincompatible-function-pointer-types]
   &compare_d,
   ^~~~~~~~~~
src/math/ltm_desc.c:449:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long, void *)' with an expression of type 'int (*)(void *, ltc_mp_digit, void *)' (aka 'int (*)(void *, unsigned long long, void *)') [-Wincompatible-function-pointer-types]
   &addi,
   ^~~~~
src/math/ltm_desc.c:451:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long, void *)' with an expression of type 'int (*)(void *, ltc_mp_digit, void *)' (aka 'int (*)(void *, unsigned long long, void *)') [-Wincompatible-function-pointer-types]
   &subi,
   ^~~~~
src/math/ltm_desc.c:453:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long, void *)' with an expression of type 'int (*)(void *, ltc_mp_digit, void *)' (aka 'int (*)(void *, unsigned long long, void *)') [-Wincompatible-function-pointer-types]
   &muli,
   ^~~~~
src/math/ltm_desc.c:457:4: warning: incompatible function pointer types initializing 'int (*)(void *, unsigned long, unsigned long *)' with an expression of type 'int (*)(void *, ltc_mp_digit, ltc_mp_digit *)' (aka 'int (*)(void *, unsigned long long, unsigned long long *)')
      [-Wincompatible-function-pointer-types]
   &modi,
   ^~~~~
6 warnings and 1 error generated.
make: *** [src/math/ltm_desc.o] Error 1

After a make clean I used this...

$ CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" make -j5 -f makefile.shared all EXTRALIBS=/usr/local/lib/libtommath.a

**Comment by sjaeckel** [comment]
> And then this happened while compiling ltm_desc.c  (LTC_MILLER_RABIN_REPS undefined)

after seeing the other warnings it looks like you have an older version already installed and your toolchain used those header files... (which reminds me that we need an `uninstall` make target)...

> Off topic: LTM goes too far the other way.  Because sources are top level, so are the .o and .lo files.  No need for any extra reminder to run "make clean".

yeah I once started, but never finished, to move all sources of LTM neatly into folders like TFM has it...

> I understand and accept.
> 
> ...but I reserve the right to not like it. ;-)

... you will get used to it :P

**Comment by sjaeckel** [comment]
added `make uninstall` for `makefile` and `makefile.shared` 221f7f223db5cf570c4d3c9faf8e6857d1b9ab53

**Comment by karel-m** [comment]
Would not it be better to properly arrange `-I` order?
```
gcc -DUSE_LTM -DLTM_DESC -I/usr/local/include -I./src/headers/
vs.
gcc -DUSE_LTM -DLTM_DESC -I./src/headers/ -I/usr/local/include
```

Can anybody please test on MacOS a simplified generic UNIX build (only static lib) via `make -f makefile.unix` ?

**Comment by sjaeckel** [comment]
> Would not it be better to properly arrange -I order?

most likely yes

> Can anybody please test on MacOS a simplified generic UNIX build (only static lib) via make -f makefile.unix ?

works fine on latest `release/1.18.0`

when I try to do `make -f makefile.unix hashsum` it complains that it doesn't find `../libtommath/libtommath.a` even though `hashsum` doesn't need a math library... `make -f makefile.unix hashsum EXTRALIBS=" "` did the job...

**Comment by sjaeckel** [comment]
> Would not it be better to properly arrange -I order?

96364c87d21c13b838d369de1e5202d55d53d02b fine like that?

**Comment by rofl0r** [comment]
> bug fixed 3806629

thanks! confirmed working. i also tried DESTDIR and it works as intended. great!

> The following 4 points are due to the historical way how libtomcrypt was always distributed

i understand your stance, OTOH you now have the chance to get rid of historical mistakes rather than carrying them forward =)

> regarding the doc@terminal: e767451 fine?

i don't know that format, and what kind of viewer you need to look at it, so i can't comment on that.

> Edit: or do you know a way to convert the latex documentation to e.g. man pages?

no. i guess it would be nice to have generated manpages contained in the release tarball though. however the information i'm after (build instructions) is imo best provided in raw text format, since it's not straightforward to look at manpage until they're installed into the system's default manpage path (usually $PREFIX/share/man/manX). there are some `man` implementations that accept a file path (like `man docs/foo.3`), but afaict that usage is not supported by all of them.

> yeah, the PDF is pretty big, but falls in the category "distribute everything"

libtom is usually used for "embedded" applications (i.e. small size is important), so imo it would be good if the source is small too. i'm quite sure that of 100 people downloading a source tarball, less than a handful is also interested in reading developer documentation.

a good example for having the documentation split into a separate package is git.
software itself is in http://cdn.kernel.org/pub/software/scm/git/git-2.13.1.tar.xz
manpages are in http://cdn.kernel.org/pub/software/scm/git/git-manpages-2.13.0.tar.xz
(i am pretty happy that git guys ship the generated manpages instead of having a by-default-enabled makefile target that builds the documentation using some obscure documentation tool, which would force the user to install that, and all its dependencies too, just to get the software compiled).
counterexample is curl: before release 7.51.0 the source tarball was 6MB, afterwards 21MB since they stuffed some pdfs and html into the tarball. not nice :/

**Comment by buggywhip** [comment]
Arguably I shouldn't have to, but I added -I./src/headers/ to the command CFLAGS="-DUSE_LTM -DLTM_DESC -I./src/headers/ -I/usr/local/include" make -j5 -f makefile.shared all EXTRALIBS=/usr/local/lib/libtommath.a and got the following 6 errors and 8 warnings.  

tests/pkcs_1_oaep_test.c:19:31: warning: declaration shadows a variable in the global scope [-Wshadow]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                              ^
/usr/local/include/tomcrypt_test.h:83:41: note: previous declaration is here
extern const struct ltc_prng_descriptor no_prng_desc;
                                        ^
tests/pkcs_1_oaep_test.c:19:46: warning: implicit declaration of function 'no_prng_desc_get' is invalid in C99 [-Wimplicit-function-declaration]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                                             ^
tests/pkcs_1_oaep_test.c:19:31: warning: incompatible integer to pointer conversion initializing 'struct ltc_prng_descriptor *' with an expression of type 'int' [-Wint-conversion]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                              ^              ~~~~~~~~~~~~~~~~~~
tests/pkcs_1_oaep_test.c:61:3: warning: implicit declaration of function 'no_prng_desc_free' is invalid in C99 [-Wimplicit-function-declaration]
  no_prng_desc_free(no_prng_desc);
  ^
tests/pkcs_1_pss_test.c:19:31: warning: declaration shadows a variable in the global scope [-Wshadow]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                              ^
/usr/local/include/tomcrypt_test.h:83:41: note: previous declaration is here
extern const struct ltc_prng_descriptor no_prng_desc;
                                        ^
tests/pkcs_1_pss_test.c:19:46: warning: implicit declaration of function 'no_prng_desc_get' is invalid in C99 [-Wimplicit-function-declaration]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                                             ^
tests/pkcs_1_pss_test.c:19:31: warning: incompatible integer to pointer conversion initializing 'struct ltc_prng_descriptor *' with an expression of type 'int' [-Wint-conversion]
  struct ltc_prng_descriptor* no_prng_desc = no_prng_desc_get();
                              ^              ~~~~~~~~~~~~~~~~~~
tests/pkcs_1_pss_test.c:62:3: warning: implicit declaration of function 'no_prng_desc_free' is invalid in C99 [-Wimplicit-function-declaration]
  no_prng_desc_free(no_prng_desc);
  ^


tests/test.c:27:19: error: use of undeclared identifier 'mpi_test'
      LTC_TEST_FN(mpi_test),
                  ^
tests/test.c:31:19: error: use of undeclared identifier 'der_test'
      LTC_TEST_FN(der_test),
                  ^
tests/test.c:48:19: error: use of undeclared identifier 'prng_test'; did you mean 'sprng_test'?
      LTC_TEST_FN(prng_test),
                  ^~~~~~~~~
                  sprng_test
tests/test.c:15:27: note: expanded from macro 'LTC_TEST_FN'
#define LTC_TEST_FN(f)  { f, #f }
                          ^
./src/headers/tomcrypt_prng.h:192:6: note: 'sprng_test' declared here
int  sprng_test(void);
     ^
tests/test.c:59:16: error: static declaration of 'epoch_usec' follows non-static declaration
static ulong64 epoch_usec(void)
               ^
/usr/local/include/tomcrypt_test.h:93:9: note: previous declaration is here
ulong64 epoch_usec(void);
        ^
tests/test.c:333:26: error: invalid application of 'sizeof' to an incomplete type 'const test_function []'
   for (i = 0; i < sizeof(test_functions) / sizeof(test_functions[0]); ++i) {
                         ^~~~~~~~~~~~~~~~
tests/test.c:354:26: error: invalid application of 'sizeof' to an incomplete type 'const test_function []'
   for (i = 0; i < sizeof(test_functions)/sizeof(test_functions[0]); ++i) {
                         ^~~~~~~~~~~~~~~~

And I submit the -I./src/headers/ should be a default inside the makefile.  Yes?

Note: the previous undefined LTC_MILLER_RABIN_REPS error went away.

**Comment by karel-m** [comment]
The trouble in IMO `/usr/local/include/tomcrypt_test.h`

**Comment by sjaeckel** [comment]
> The trouble in IMO /usr/local/include/tomcrypt_test.h

very true, @buggywhip now you really have to clean up the previous installation ;-) tomcrypt_test.h (and lib/libtomcrypt_prof.a) isn't installed anymore and collides with the new internal API's...

**Comment by sjaeckel** [comment]
> OTOH you now have the chance to get rid of historical mistakes rather than carrying them forward =)

yep, that's also some kind of true, but we decided some weeks/months ago to make this the last release of the v1 branch and clean up for the next release, which also most likely brings some API breakage.

> i don't know that format, and what kind of viewer you need to look at it, so i can't comment on that.

well that just displays the dvi on the terminal, so you don't need a graphical UI :-) 

> i guess it would be nice to have generated manpages contained in the release tarball though

"would be nice" is good ;-)

> the information i'm after (build instructions) is imo best provided in raw text format

I'll add it to the README, #197 already has a task

> i'm quite sure that of 100 people downloading a source tarball, less than a handful is also interested in reading developer documentation

probably true

> ...imo it would be good if the source is small too...
> ...a good example for having the documentation split into a separate package is git

also most likely true, we will think about a way to split everything up for v2

A short note:

I loved the way the releases were done before, by simply including everything in a tarball. We would've had to reverse engineer how a lot of things were done, resp. re-write huge parts of the build system etc. (which probably sometimes would've been a good idea as well ;-) ). Now it is as it is, kept to not break that much from the process that the last release was based on and we can look forward and improve all those parts that have changed the way how they're done in the last 10 years...

**Comment by sjaeckel** [comment]
http://www.libtom.net/news/LTC_1.18RC2/
