### ISSUE TITLE
tomcrypt_cfg.h detects the wrong endianness with gcc-arm-none-eabi-5_4-2016/q3

### ISSUE THREAD

**Issue by clarkli86** [libtom/libtomcrypt#254]
gcc-arm-none-eabi-5_4-2016q3/arm-none-eabi/include/machine/_endian.h sets _BYTE_ORDER to either _BIG_ENDIAN or _LITTLE_ENDIAN, but tomcrypt_cfg.h always thinks the target is big endian because _BIG_ENDIAN is defined. As a result libtomcrypt is compiled with big endian for a little endian platform.

Content of _endian.h
```
#ifndef __MACHINE_ENDIAN_H__
#error "must be included via <machine/endian.h>"
#endif /* !__MACHINE_ENDIAN_H__ */

#define»_LITTLE_ENDIAN»·1234
#define»_BIG_ENDIAN»4321
#define»_PDP_ENDIAN»3412

#ifdef __ARMEB__
#define»_BYTE_ORDER»_BIG_ENDIAN
#else
#define»_BYTE_ORDER»_LITTLE_ENDIAN
#endif

```

Suggested fix: Fully check __BYTE_ORDER for big endian/little endian before checking #if defined(__BIG_ENDIAN__)

**Comment by karel-m** [comment]
On Jul 31, 2017 2:29 PM, "Clark Li" <notifications@github.com> wrote:

gcc-arm-none-eabi-5_4-2016q3/arm-none-eabi/include/machine/_endian.h sets
_BYTE_ORDER to either _BIG_ENDIAN or _LITTLE_ENDIAN, but tomcrypt_cfg.h
always thinks the target is big endian because _BIG_ENDIAN is defined. As a
result libtomcrypt is compiled with big endian for a little endian platform.

Content of _endian.h

#ifndef __MACHINE_ENDIAN_H__
#error "must be included via <machine/endian.h>"
#endif /* !__MACHINE_ENDIAN_H__ */

#define»_LITTLE_ENDIAN»·1234
#define»_BIG_ENDIAN»4321
#define»_PDP_ENDIAN»3412

#ifdef __ARMEB__
#define»_BYTE_ORDER»_BIG_ENDIAN
#else
#define»_BYTE_ORDER»_LITTLE_ENDIAN
#endif


Suggested fix: Fully check __BYTE_ORDER for big endian/little endian before
checking #if defined(*BIG_ENDIAN) *


__BYTE_ORDER is IMO fully checked (see below), however earlier in your text
you talk about _BYTE_ORDER (single leading underscore)

```

/* endianness fallback */
#if !defined(ENDIAN_BIG) && !defined(ENDIAN_LITTLE)
  #if defined(__BYTE_ORDER) && __BYTE_ORDER == __BIG_ENDIAN || \
      defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__ || \
      defined(__BIG_ENDIAN__) || defined(_BIG_ENDIAN) || \
      defined(__ARMEB__) || defined(__THUMBEB__) || defined(__AARCH64EB__) || \
      defined(_MIPSEB) || defined(__MIPSEB) || defined(__MIPSEB__)
    #define ENDIAN_BIG
  #elif defined(__BYTE_ORDER) && __BYTE_ORDER == __LITTLE_ENDIAN || \
      defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__ || \
      defined(__LITTLE_ENDIAN__) || defined(_LITTLE_ENDIAN) || \
      defined(__ARMEL__) || defined(__THUMBEL__) || defined(__AARCH64EL__) || \
      defined(_MIPSEL) || defined(__MIPSEL) || defined(__MIPSEL__)
    #define ENDIAN_LITTLE
  #else
    #error Cannot detect endianness
  #endif
#endif

```

**Comment by rofl0r** [comment]
all recent GCC's (iirc >= 4.8.0) define `__BYTE_ORDER__` even when no header is included for the arch they're compiled for:

```
$ i486-linux-musl-gcc -dM -E - </dev/null| grep BYTE_O
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
```
so it could make sense to check this at the very beginning, and if not defined fall back to endian.h and only at last to all the hardcoded archs...

**Comment by sjaeckel** [comment]
> so it could make sense to check this at the very beginning, and if not defined fall back to endian.h and only at last to all the hardcoded archs...

... luckily I didn't propose exactly this when re-working that part https://github.com/libtom/libtomcrypt/pull/109#issuecomment-282017635 ;-) ... which then got replaced by the 'battle-tested' version that's in use now ...

**Comment by karel-m** [comment]
Regardless whether we do the endianness check at the beginning or at the
end we definitely have to add a test for:

defined(_BYTE_ORDER) && _BYTE_ORDER == _BIG_ENDIAN

And perhaps leave out the part:

¦¦ defined(_BIG_ENDIAN) ¦¦

Or maybe replace it with:

defined(_BIG_ENDIAN) && !defined(_LITTLE_ENDIAN)

**Comment by sjaeckel** [comment]
okay like that?

**Comment by sjaeckel** [comment]
@clarkli86 can you please checkout fix/254 and give it a try?

**Comment by karel-m** [comment]
I would keep:

defined(__BIG_ENDIAN__)

and the same for __LITTLE_ENDIAN__

https://sourceforge.net/p/predef/wiki/Endianness/

**Comment by sjaeckel** [comment]
better?!

**Comment by karel-m** [comment]
Yes, looks good.

**Comment by karel-m** [comment]
I propose merging `fix/254` branch

**Comment by karel-m** [comment]
now in branch `release/1.18.0`

closing
