### ISSUE TITLE
Cannot build 1.18.0 with uClibc

### ISSUE THREAD

**Issue by fperrad** [libtom/libtomcrypt#313]
On [Buildroot](https://buildroot.org/), we detect build failures when using [uClibc-ng](https://uclibc-ng.org/), see <http://autobuild.buildroot.org/?reason=libtomcrypt-1.18.0>.
The build.log shows a conflict with `wchar_t`
```
In file included from ./src/headers/tomcrypt.h:88:0,
                 from src/ciphers/anubis.c:16:
./src/headers/tomcrypt_pk.h:678:17: error: conflicting types for 'wchar_t'
 typedef ulong32 wchar_t;
                 ^~~~~~~
In file included from ./src/headers/tomcrypt.h:16:0,
                 from src/ciphers/anubis.c:16:
/usr/lfs/v0/rc-buildroot-test/scripts/instance-2/output/host/opt/ext-toolchain/lib/gcc/arm-buildroot-linux-uclibcgnueabi/6.3.0/include/stddef.h:328:24: note: previous declaration of 'wchar_t' was here
 typedef __WCHAR_TYPE__ wchar_t;
                        ^~~~~~~
```

This piece of code https://github.com/libtom/libtomcrypt/blob/develop/src/headers/tomcrypt_pk.h#L669-L680 is not suitable with uClibc.

**Comment by karel-m** [comment]
Your CFLAGS:
```
CFLAGS="-I./src/headers -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -DLTC_SOURCE -DLTM_DESC -DLTC_NO_WCHAR"
```

Does the build fail if you remove `-DLTC_NO_WCHAR`?

**Comment by rofl0r** [comment]
>./src/headers/tomcrypt_pk.h:678:17: error: conflicting types for 'wchar_t'
> typedef ulong32 wchar_t;

sounds like a pretty bad idea to define standard C types in your own headers.

quick guess, it is the result of ifdef hacks (or making ifdef hacks work) because you lack proper configure-style tests to check for properties of a certain implementation.

**Comment by fperrad** [comment]
It seems the issue could be solved on Buildroot side, see https://patchwork.ozlabs.org/patch/826925/

I'll close this issue when it disappears on http://autobuild.buildroot.org

**Comment by sjaeckel** [comment]
uhm, not sure though what triggered this error, but the (now) failing part is already since 1.16 in ltc... 

> sounds like a pretty bad idea to define standard C types in your own headers.

very true

> quick guess, it is the result of ifdef hacks (or making ifdef hacks work) because you lack proper configure-style tests to check for properties of a certain implementation.

A side-note to this recurring topic: TBH a lot of my use-cases of ltc included platforms where no configure-style toolchain is easily available (AFAIK) and it always worked OOTB - that was and still is one of the strengths of all the libtom projects in my opinion.
And as already said, I'd be open to merge patches adding support for configure, cmake, whatever tool that thinks it can solve this kind of problems, but I've one side-requirement: I want to be able to build the library still OOTB resp. there have to be default-configs easily available that handle those platforms where I currently was able to throw the library sources in and build the library. (and yes... I sadly speak of stuff like the Xilinx Vivado Toolchain on Windows where not even one of the makefiles worked but at least I could create a new Xilinx-flavored Eclipse project in the src folder, set the include path and build the library...)

**Comment by karel-m** [comment]
The trouble here is that `LTC_NO_WCHAR` sounds like "skip all wchar related parts"; however in fact it means "my system is missing wchar, try to define one".

**Comment by karel-m** [comment]
Can we close this?

**Comment by sjaeckel** [comment]
well http://autobuild.buildroot.org/?reason=libtomcrypt-1.18.0 still shows failing builds

**Comment by karel-m** [comment]
All those failures use `-DLTC_NO_WCHAR` but they shouldn't

**Comment by fperrad** [comment]
On Buildroot, a [fix](https://git.busybox.net/buildroot/commit/?id=2f256545044762877129027bec1518669dcd7b7d) was authored on 2017-10-17, and commited on 2017-10-22.
There is no new occurrence of this failure after the 2017-10-22.
So, it is OK for me.
