### ISSUE TITLE
use of libcrypt

### ISSUE THREAD

**Issue by userwzm** [libtom/libtomcrypt#492]
when I build the project,it always failed,one problem is cannot open tommath.h ,so how solve this,thanks.

**Comment by sjaeckel** [comment]
Can you please give more details about the issue? Such as the compiler used, the architecture to build for and building on and the version of the library.

**Comment by userwzm** [comment]
I choose vs2008 and  the version of the library is crypt-1.18.2,I want to know whether tommath.h is in ltm-1.1.0, how to include tommath.h to libtomcrypt,I search some methods on the internet ,but they all don't work, if you can help me,you could send an e-mail to me,my e-mail is15650750065@163.com,thanks.

**Comment by karel-m** [comment]
You have to unpack libtomcrypt and libtommath source codes into directories like this:
```
c:\some\directory\libtommath
c:\some\directory\libtomcrypt
```

Which means you have `c:\some\directory\libtommath\tommath.h`. With this directory layout the `c:\some\directory\libtomcrypt\libtomcrypt_VS2008.sln` should work out of box.

However, be aware of the fact that Visual Studio 2008 (and earlier) is not supported by the latest libtommath due to dependency on `stdint.h`. You can try unofficial hacked version available at https://github.com/libtom/libtommath/archive/no-stdint-h-v1.1.0.zip

**Comment by userwzm** [comment]
thanks,I will try

**Comment by userwzm** [comment]
if you mean that I can use vs2008 open the libtomcrypt_VS2008.sln directly,my problem is when I debug it
I will  come across some  issues.

**Comment by userwzm** [comment]
fatal error C1083: :“tommath.h”: No such file or directory	d:\vs2008\doucment\libtomcrypt-develop\libtomcrypt-develop\src\math\ltm_desc.c

**Comment by karel-m** [comment]
Rename directories to

d:\vs2008\doucment\libtomcrypt\

d:\vs2008\doucment\libtommath\

**Comment by userwzm** [comment]
ok thanks

**Comment by sjaeckel** [comment]
Please re-open if you have further questions/comments.

**Comment by userwzm** [comment]
ok, thank you very much

在 2019-07-18 02:05:05，"Steffen Jaeckel" <notifications@github.com> 写道：


Closed #492.
