### ISSUE TITLE
adding libtommath to the Libs 

### ISSUE THREAD

**Issue by apteryks** [libtom/libtomcrypt#610]
Hello,

We carry a patch in GNU Guix which modifies the pkg-config.pc.in file so that libtommath is also added to Libs (`Libs: -L${libdir} -ltomcrypt -ltommath`).

Would it make sense to be applied here (upstream) ?

Thanks!

**Comment by sjaeckel** [comment]
The issue here is that libtommath is no hard dependency but a compilation choice.

One can choose out of the following three MPI providers `libtommath`, `tomsfastmath` and `gnump` (or any combination of the three) when compiling libtomcrypt.

The bad part of the current solution is that always all configured MPI providers have to be linked ... it's only a runtime decision of the user which MPI provider to use in the end ...

Would you be fine with the proposed solution?

**Comment by apteryks** [comment]
Hi! Thanks for working on a solution; it seems sensible to me!
