### ISSUE TITLE
Conflict while using yarrow_start and find_cipher("aes")

### ISSUE THREAD

**Issue by prikevs** [libtom/libtomcrypt#66]
#include <stdio.h>
    #include <tomcrypt.h>
    int main()
    {
        int idx;
        prng_state prng;

        register_prng(&yarrow_desc);
        yarrow_start(&prng);

        register_cipher(&aes_desc);
        idx = find_cipher("aes");
        printf("idx=%d\n", idx);
        return 0;
    }

This program will output idx = -1
if without yarrow_start() or 
find_cipher() runs before yarrow_start() or
use other Cipher Descriptors, 
it will be OK.
I think there must be a conflict between the yarrow_start and aes_desc, but I cannot find the reason.

My computer is Thinkpad T430u,
OS is Ubuntu14.04
tomcrypt version is 1.17

Thanks.

**Comment by sjaeckel** [comment]
Nice find!

I didn't check it, but I suppose that's because `yarrow_start()` already registers "aes", but under the name "rijndael". Both share the same ID and `register_cipher()` first checks if there's already a cipher with the same ID registered, so it doesn't register the `aes_desc`.
Now you won't find something called "aes" :)

Try putting the `register_cipher(&aes_desc)` before the yarrow initialization and it should work as expected.

**Comment by prikevs** [comment]
Thanks.
What you said solved my problem quite well.
I think this issue need to be mentioned in the documentation, for others convenience. :-)
